### ISSUE TITLE
Where to buy the devkit? 

### ISSUE THREAD

**Issue by madushan1000** [sophgo/sophpi-duo#1]
I couldn't find a place to buy a devkit(mikv duo/CV1800B), do you sell it on aliexpress?

**Comment by aceraoc** [comment]
> I couldn't find a place to buy a devkit(mikv duo/CV1800B), do you sell it on aliexpress?

You can buy milkv in this link https://app6hodqg6k9861.h5.xiaoeknow.com/p/decorate/homepage

**Comment by madushan1000** [comment]
Thanks, but it looks like it only ships to china, I saw some on aliexpress too, but now they're all sold out. But I'll close this issue.
